### PR TITLE
Support scientific nums in humanize

### PR DESCRIPTION
**Pull request by arkal**

### CODE REVIEW

**Comment by arkal** [comment]
@hannes-ucsc this is ready!

**Comment by hannes-ucsc** [comment]
Can you describe the use case? Human2bytes is for converting metric and binary prefixes, not float to int conversion.

**Comment by arkal** [comment]
check the issue i opened in toil.... dynamic promises can produce resource requests in the float type, but in scientific format. Currently that will fail with a "cannot parse" error. This PR aims to fix that.

**Comment by hannes-ucsc** [comment]
The issue @arkal is referring to is https://github.com/BD2KGenomics/toil/issues/1063.

**Comment by hannes-ucsc** [comment]
I don't think making human2bytes grok float literals is the solution to https://github.com/BD2KGenomics/toil/issues/1063. `human2bytes` has a very distinct purpose: converting binary and metric prefixes. You need to address this in Toil. The easiest solution isn't always the best.

**Comment by arkal** [comment]
okay i'll look into it

**Pull request closed without merging**
