### PR TITLE
full py3/py2 compat

### LINKED ISSUE #17: Please support Python3
Hi,
bd2k is packaged for Debian.  Since Python2 will not be supported any more soon we would love to support Python3.  While it is possible to install the Python3 module it throws errors when using it.  Please switch to Python3 to be safe for the future.
Thank you, Andreas.

### PR DESCRIPTION
**Pull request by mr-c**
Fixes #17

### CODE REVIEW

**Comment by mr-c** [comment]
Only one failure, due to an error in `~/.boto` on the jenkins server:

http://jenkins.cgcloud.info/job/bd2k-python-lib/47/testReport/py3.src.bd2k.util.ec2.test.test_credentials/CredentialsTest/test_metadata_credential_caching/

configparser.DuplicateOptionError: While reading from '/home/jenkins/.boto' [line  9]: option 'gs_access_key_id' in section 'Credentials' already exists

**Comment by mr-c** [comment]
@ejacox Can I get a review & merge?

**Comment by ejacox** [comment]
@mr-c. Merged.

If Toil tests pass with the changes, we can do a release of this library. Otherwise, this library might be deprecated. All of the code used by Toil would be merged into the toil repository (this was what was being done with Toil PR #1937).

**Comment by mr-c** [comment]
@ejacox Thanks! How shall I go about testing Toil with these changes? Maybe you could make a pre-release here and we could test with a PR to Toil that pins bd2k-python-lib to that pre-release?

https://packaging.python.org/tutorials/distributing-packages/#pre-release-versioning

> pip and other modern Python package installers ignore pre-releases by default when deciding which versions of dependencies to install.

So it wouldn't affect users until a normal release occurs.

**Comment by ejacox** [comment]
I discussed it with @DailyDreaming. We think it would be best to deprecate this repository by copying all of the needed files from this repository into the Toil repository.

**Comment by mr-c** [comment]
Okay! Well, at least it won't introduce additional py3 incompatibilities
anymore 🙂

lun., 7 mai 2018, 22:28 Edwin Jacox <notifications@github.com> a scris:

**Pull request merged**
